site_name: Awesome Kubernetes
site_url: https://awesome-kubernetes.readthedocs.io
site_description: A curated list of awesome IT projects and resources. Inspired by the awesome list.
site_author: inafev

repo_url: https://github.com/inafev/awesome-kubernetes

theme: readthedocs
extra_css:
- extra.css
extra_javascript:
- extra.js
site_favicon: images/favicon.ico
markdown_extensions:
- smarty
- sane_lists
- fenced_code
- meta
- admonition
- toc:
    permalink: True
pages:
- Home: index.md
- Introduction. Openshift VS Kubernetes: introduction.md
- CI/CD : cicd.md
- Docker: docker.md
- Kubernetes : kubernetes.md
- Openshift : openshift.md
- List of Openshift Compliant Docker images. Demos : openshift-compliant-images.md
- Monitoring and Performance : monitoring.md
- Java and Java Performance Optimization: java-and-java-performance-optimization.md
- Troubleshooting openshift network performance: troubleshooting-openshift-network-performance.md
- Jenkins : jenkins.md
- Performance Testing with Jenkins and JMeter : performance-testing-with-jenkins-and-jmeter.md
- Jenkins and Openshift. Demos : jenkins-and-openshift.md
- Groovy: groovy.md
- Maven: maven.md
- SonarQube: sonarqube.md
- Nexus: nexus.md
- HAProxy : haproxy.md
- Payara : payara.md
- Terraform: terraform.md
- Ansible: ansible.md
- Git: git.md
- Visual Studio: visual-studio.md
- GitKraken: gitkraken.md
- Linux Dev Environment: linux-dev-env.md
- APIs and RESTful Architecture: apis-and-restful-architecture.md
- Swagger code generator for REST APIs: swagger-code-generator-for-rest-apis.md
- Public Cloud Solutions : public-cloud-solutions.md
- E-Learning: elearning.md
- Customer Success Stories: customer.md
- Newsfeeds : newsfeeds.md
- About: about.md

copyright: 2018 <a href="https://twitter.com/RedHatSpain">Red Hat Spain (Unofficial linkedin group)</a>, <a href="https://awesome-kubernetes.readthedocs.io/about/">about</a>.
google_analytics: ['UA-126665400-1', 'awesome kubernetes']
